server:
  port: 5678
spring:
  redis:
    host: 192.168.188.128
    port: 6379
  session:
    store-type: redis #session存储方式
    timeout: 5000 #session过期时间 单位：秒
  thymeleaf:
    cache: false #禁用缓存模板



